version: "3.9"

services:
  api:
    build: .
    container_name: palm_minds_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_DSN: ${DATABASE_DSN}
      REDIS_URL: ${REDIS_URL}
      QDRANT_URL: ${QDRANT_URL}
      EMBEDDING_API_KEY: ${EMBEDDING_API_KEY}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
    depends_on:
      - redis
      - mysql
      - qdrant
    volumes:
      - .:/app  

  redis:
    image: redis:7
    container_name: palm_minds_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: palm_minds_mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - palm_minds_mysql_data:/var/lib/mysql

  qdrant:
    image: qdrant/qdrant:latest
    container_name: palm_minds_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - palm_minds_qdrant_data:/qdrant/storage

volumes:
  palm_minds_mysql_data:
  palm_minds_qdrant_data:
